=== BarbutaDelia/NFT-visualizer/continut/resurse/NFTs.dtd
<!ELEMENT NFTs (NFT)*>
<!ELEMENT NFT (name|price|rank|properties)*>
<!ATTLIST NFT
    id CDATA #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT rank (#PCDATA)>
 <!ELEMENT properties (headwear|body|background|type)*>
<!ELEMENT headwear (#PCDATA)>
<!ELEMENT body (#PCDATA)>
<!ELEMENT background (#PCDATA)>
<!ELEMENT type (#PCDATA)>

=== BarbutaDelia/NFT-visualizer/continut/resurse/NFTs.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE NFTs SYSTEM "NFTs.dtd">
<NFTs>
    <NFT id="1">
        <name>Cowboy Bone</name>
        <price>0.8 eth</price>
        <rank>3/3</rank>
        <properties>
            <headwear>Slouch Hat</headwear>
            <body>YPBP Sweatshirt</body>
            <background>Yellow Gree</background>
            <type>Funny Bone</type>
        </properties>
    </NFT>
    <NFT id="2">
        <name>Afro Bone</name>
        <price>1.18 eth</price>
        <rank>2/3</rank>
        <properties>
            <headwear>Dreadlocks</headwear>
            <body>Ancient Armor</body>
            <background>Light Blue</background>
            <type>Meaty Bone</type>
        </properties>
    </NFT>
    <NFT id="3">
        <name>Sleepless Bone</name>
        <price>1.7 eth</price>
        <rank>1/3</rank>
        <properties>
            <headwear>Dreadlocks</headwear>
            <body>Hoodie</body>
            <background>Navy Green</background>
            <type>Speedy Bone</type>
        </properties>
    </NFT>
</NFTs>
